### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by 99hats** [vassilych/mobile#1]
Howdy,

Very interesting project. I've started using CSCS in a small side project, very fun and adaptable!

I'm having a few issues with the install of the mobile example on android:

    Error MSB3030: Could not copy the file "Resources\layout\spinner.axml" because it was not found. (1, 1)
    Error MSB3030: Could not copy the file "Resources\values-es\Strings.xml" because it was not found. (1, 1)
    Error MSB3030: Could not copy the file "Resources\values\style.xml" because it was not found. (1, 1)
    Error MSB3030: Could not copy the file "..\scripting\Resources\drawable\Launch2208.png" because it was not found. (1, 1)

**Comment by vassilych** [comment]
Howdy, thanks a lot for your feedback. I uploaded a few missing files. BTW you can also check out the project zip file in the Root git directory - it should have all the files except the packages.
Let me know if it now  works for you.

Cheers,
Vassili
